name: Read Secret Workflow

on:
  workflow_dispatch:

jobs:
  trigger-tekton-pipeline-with-secret:
    name: Trigger Tekton Pipeline with Secret
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Pipeline
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"secret": "${{ secrets.MY_SECRET_NAME }}"}' \
            ${{ secrets.OCP_TEKTON_WEBHOOK_URL }}
        env:
          MY_SECRET_NAME: ${{ secrets.MY_SECRET_NAME }}
          OCP_TEKTON_WEBHOOK_URL: ${{ secrets.OCP_TEKTON_WEBHOOK_URL }}
